[package]
name = "tabs"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.33"
eframe = { version = "0.33", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "wgpu",
    "persistence",
] }
log = "0.4"
egui_term = { git = "https://github.com/Harzu/egui_term" }
wgpu = "27"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.6"

[features]
default = []
x11 = ["eframe/x11"]
wayland = ["eframe/wayland"]
